import React from 'react';

export function DocumentHeader({ title }: { title?: string }) {
  return (
    <div style={{ textAlign: 'center', marginBottom: '24px', borderBottom: '2px solid var(--gov-blue)', paddingBottom: '18px' }}>
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '12px', marginBottom: '12px', flexWrap: 'wrap' }}>
        {/* Official Logo */}
        <div style={{ 
          width: '64px', height: '64px', 
          border: '2px solid var(--muted-gold)', 
          borderRadius: '50%', 
          display: 'flex', justifyContent: 'center', alignItems: 'center', 
          backgroundColor: '#fff',
          boxShadow: 'inset 0 0 10px rgba(197, 168, 128, 0.2)',
          padding: '3px',
          overflow: 'hidden'
        }}>
          <img src="/logo.png" alt="Logo" style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
        </div>
        
        <div style={{ textAlign: 'center' }}>
          <h1 style={{ margin: '0 0 2px 0', color: 'var(--gov-blue)', fontSize: 'clamp(1.2rem, 3.5vw, 1.8rem)', letterSpacing: '2px', fontFamily: 'var(--font-family-serif)' }}>
            PAZAMAYI SHERIYAYI
          </h1>
          <div style={{ color: 'var(--muted-gold-dark)', fontSize: '0.75rem', letterSpacing: '2px', textTransform: 'uppercase', fontWeight: 'bold' }}>
            Identify • Analyse • Verify
          </div>
        </div>
      </div>
      
      {title && (
        <h2 style={{ margin: '12px 0 0 0', fontSize: 'clamp(1.1rem, 2.5vw, 1.4rem)', textTransform: 'uppercase', color: 'var(--text-dark)', letterSpacing: '1px' }}>
          {title}
        </h2>
      )}
    </div>
  );
}

export function DocumentFooter({ documentNumber, qrReference }: { documentNumber: string, qrReference?: string }) {
  return (
    <div style={{ marginTop: '32px', borderTop: '2px solid var(--gov-blue)', paddingTop: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', fontSize: '0.75rem', color: 'var(--text-light)', flexWrap: 'wrap', gap: '16px' }}>
      <div style={{ flex: '1 1 200px' }}>
        <div style={{ fontWeight: 'bold', color: 'var(--gov-blue)', fontSize: '0.85rem', wordBreak: 'break-all' }}>{documentNumber}</div>
        <div>Digitally generated by Banana Documentation Division</div>
        <div style={{ fontStyle: 'italic', marginTop: '4px', fontSize: '0.7rem' }}>Fictional digital registry system • Official Document Record</div>
      </div>
      {qrReference && (
        <div style={{ textAlign: 'center', marginLeft: 'auto' }}>
          <div style={{ width: '70px', height: '70px', backgroundColor: '#000', margin: '0 auto 4px auto', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
             {/* Fake QR visual block */}
             <div style={{ width: '62px', height: '62px', backgroundColor: '#fff', display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '1px', padding: '2px' }}>
                 {Array.from({ length: 25 }).map((_, i) => <div key={i} style={{ backgroundColor: ((i * 7) % 11) > 5 ? '#000' : '#fff' }} />)}
             </div>
          </div>
          <div style={{ fontFamily: 'monospace', fontSize: '0.65rem' }}>SCAN TO VERIFY</div>
        </div>
      )}
    </div>
  );
}
